#!/bin/sh

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

pipewire &
sleep 1 &&
wireplumber &
sleep 1 &&
pipewire-pulse &

#env GALLIUM_HUD=help picom --legacy-backend &

#tint2 &
#xmodmap .Xmodmap &
xrdb .Xresources &

#xrandr --output DVI-I-0 --mode 1440x900 --rate 75
#xrandr --output LVDS-1 --set "scaling mode" "Full"

#xinput set-prop 10 314 0
