#!/bin/bash
if [ "$1" = "-m" ]; then
  :
elif [ -z "${2}" ]; then
  printf "${c0}ERROR:${NC} Please provide number of steps\n"
  exit
fi
vol=${2}

vn()
{
notify-send -r 666 -i . -h int:value:$(pamixer --get-volume) "Volume: $(pamixer --get-volume)%"
}

vmn()
{
if [[ $(pamixer --get-mute) == "true" ]]; then
  notify-send -r 666 -i . -h int:value:$(pamixer --get-volume) "Volume: $(pamixer --get-volume)% (Muted)"
else
  vn
fi
}

i()
{
pamixer -i $vol && vn
}

d()
{

pamixer -d $vol && vn
}

m()
{
pamixer -t && vmn
}

while getopts ":idm" option; do
   case $option in
      i)
         i
         exit;;
      d)
         d
         exit;;
      m)
         m
         exit;;
esac done
